# Generated by Selenium IDE
require 'rails_helper'
require 'selenium-webdriver'
require 'json'
describe 'Untitled' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'untitled' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.manage.resize_to(1200, 750)
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('1')
    @driver.find_element(:name, 'commit').click
    element = @driver.find_element(:name, 'commit')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(By.CSS_SELECTOR, 'body')
    @driver.action.move_to_element(element, 0, 0).perform
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('2')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('3')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('4')
    @driver.find_element(:name, 'commit').click
    @driver.close
  end
end
